redirect mobile signup
svIndicium/site pull request #31
Opened 2023-10-25 19:05 UTC by olivierverwoerd

2023-10-26 13:49 UTC, NorthLake requested changes

2023-10-26 13:49 UTC, NorthLake commented on src/components/Hero.vue
> +        <a class="button primary rounded" href="/lid-worden">Word lid</a>
Pls als je linkt naar een andere pagina op de site, gebruik dan `<router-link to="/pagina">tekst</router-link>`. Op die manier worden de components dynamisch omgewisseld ipv dat alle javascript opnieuw geladen wordt.
```suggestion
        <router-link class="button primary rounded" to="/lid-worden">Word lid</router-link>
```

2023-11-02 13:17 UTC, NorthLake commented
> Het idee van deze link is juist om extern te gaan omdat deze vooral op mobiel gezien wordt en de /lidworden pagina werkt niet goed op mobiel.

Dit zorgt ervoor dat de redirect plaats vindt op /lid-worden zelf op basis van of de client een mobiel is. Daarom kunnen links en buttons naar lid worden ook gewoon naar `/lid-worden`. En om dat smoother te maken is het beter om router-links te gebruiken.

2023-11-02 14:58 UTC, olivierverwoerd commented
De replace functie zorgt ervoor dat dit blijft werken met de back button

2023-12-18 12:12 UTC, merged