beter layout bestuur pagina mobiel
svIndicium/site pull request #32
Opened 2023-10-25 19:19 UTC by olivierverwoerd

![image](https://github.com/svIndicium/site/assets/22635990/d8a2c73b-b63f-4c1f-a4e4-6e4c1af3719f)

2023-10-25 19:24 UTC, GreenMan36 commented
![Screenshot_2023-10-25-21-23-46-61_984e1414ae90666a90f12ff17ec14a7f.jpg](https://github.com/svIndicium/site/assets/5887406/e133d60d-5628-4707-8600-ac56ad9b9e87)

Probeer het nog eens

2023-10-25 19:27 UTC, olivierverwoerd commented
ik heb alleen telefoon gefixed. volgensmij ben jij de blame voor deze pagina

2023-10-25 20:44 UTC, olivierverwoerd commented
![image](https://github.com/svIndicium/site/assets/22635990/4f43fe1d-ff53-4fcc-9fbc-96d7cc6a560c)

2023-10-26 13:56 UTC, NorthLake commented
Tekst staat voor mij om en om rechts / midden gecentreerd.
![image](https://github.com/svIndicium/site/assets/20684682/11494139-b152-4276-8eb8-d56f0051338e)

2023-12-18 11:06 UTC, GreenMan36 commented
Heb zojuist een kleine push gedaan om de image borders en zoom te krijgen die ook op andere pagina's te vinden is.

2023-12-18 11:10 UTC, GreenMan36 requested changes
Het zou fijn zijn als de styling meer overeenkomt met de [Dispuut](https://svindicium.nl/dispuut), [Commissies](https://svindicium.nl/commissies), [Contact](https://svindicium.nl/contact) en [Home](https://svindicium.nl/) pagina's.
Daarmee refereer ik naar de image randen, hover effecten en cards.

Als dat snel lukt zou dat top zijn maar het belangrijkste is dat de layout op mobiel en desktop goed werkt, op het moment is dat niet zo.

2023-12-18 11:11 UTC, GreenMan36 commented on src/content/boards.json
>          "name": "Henk van den Dag",
Henk voor den Dag*

2023-12-19 10:41 UTC, siard-y commented
Bestuur pagina is nu min of meer gefixt

2023-12-20 16:59 UTC, olivierverwoerd commented
Topper

2023-12-20 17:00 UTC, merged